import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
   const user = await prisma.user.create({
    data: {
      name: '정뽀송',
      email: '1234@example.com',
      password: '12345678', // 해시 비밀번호 권장
      gender: 'male',            // male, female, other 중 선택
      birthdate: new Date('2000-01-01'),
      usertype: 'customer',
      signupVerifyToken: 'token123',
      isVerified: true,
      bubbleCount: 0,
      travelDistance: 0,
      rentCount: 0,
    },
  });

  console.log('User created:', user);

  const stations = await prisma.station.createMany({
    data: [
      {
        name: '시청역 4번출구점',
        address: '서울특별시 중구 시청역 근처',
        latitude: 37.566809,
        longitude: 126.977518,
        initial_umbrella_count: 30,
        current_umbrella_count: 30,
        max_umbrella_capacity: 50,
      },
      {
        name: '시청역 7번출구점',
        address: '서울특별시 중구 시청역 근처',
        latitude: 37.564344,
        longitude: 126.977249,
        initial_umbrella_count: 30,
        current_umbrella_count: 30,
        max_umbrella_capacity: 50,
      },
      // 추가 스테이션도 여기 배열에 계속 넣으면 됨
    ],
    skipDuplicates: true, // 같은 name이 있으면 무시
  });

  console.log('✅ Station created:', stations); 

  // Hashtags 미리 생성
  await prisma.hashtag.createMany({
    data: [
      { id:1, tag_name: 'hot' },
      { id:2, tag_name: 'cool' },
      { id:3, tag_name: 'cafe' },
      { id:4, tag_name: 'rain' },
    ],
    skipDuplicates: true, // 중복 무시
  });

  // Store 데이터 삽입
  await prisma.store.createMany({
    data: [
      {
        id: 1,
        name: '서시: 별을 노래하는 마음으로',
        latitude: 37.564203,
        longitude: 126.973925,
        description: null,
        address: '서울특별시 중구 덕수궁길 61',
        category: 'culture',
        image_url:
          'https://static-edge.kiaf.org/web/2025/03/26092710/%ED%8F%AC%EC%8A%A4%ED%84%B0_%EC%9B%B9%EC%9A%A9.jpg',
      },
      {
        id: 2,
        name: '향수(鄕愁), 고향을 그리다',
        latitude: 37.57925,
        longitude: 126.980464,
        description: null,
        address: '서울특별시 종로구 삼청로 30',
        category: 'culture',
        image_url:
          'https://www.art-culture.co.kr/data/editor/2508/5d7272e81eba18ff1094901c05fa7319_1755232121_6635.png',
      },
      {
        id: 3,
        name: '문화가 흐르는 서울광장',
        latitude: 37.565742,
        longitude: 126.978642,
        description: null,
        address: '서울특별시 중구 세종대로 110',
        category: 'culture',
        image_url: null,
      },
      {
        id: 4,
        name: '2025 대학미술제 : 캔버스 리그',
        latitude: 37.568001,
        longitude: 126.976349,
        description: null,
        address: '서울특별시 중구 태평로1가 60-15',
        category: 'culture',
        image_url: null,
      },
      {
        id: 5,
        name: '호아킨 소로야: 댄싱 인 더 선라이트',
        latitude: 37.564557,
        longitude: 126.982988,
        description: null,
        address: '서울특별시 중구 남대문로 73 에비뉴엘 9층',
        category: 'culture',
        image_url: null,
      },
      {
        id: 6,
        name: '청춘만발',
        latitude: 37.566844,
        longitude: 126.97602,
        description: null,
        address: '서울특별시 중구 소공동 세종대로19길 16',
        category: 'culture',
        image_url: null,
      },
      {
        id: 7,
        name: '칸티쿰합창단 제41회 정기연주회',
        latitude: 37.566988,
        longitude: 126.976084,
        description: null,
        address: '서울특별시 중구 세종대로21길 15',
        category: 'culture',
        image_url: null,
      },
      {
        id: 8,
        name: '서울 도서관',
        latitude: 37.566227,
        longitude: 126.97782,
        description: null,
        address: '서울특별시 중구 세종대로 110',
        category: 'culture',
        image_url: null,
      },
      {
        id: 9,
        name: '유림면',
        latitude: 37.564214,
        longitude: 126.976084,
        description: null,
        address: '서울특별시 중구 서소문로 139-1',
        category: 'recommendation',
        image_url: null,
      },
      {
        id: 10,
        name: '서울 삼계탕',
        latitude: 37.563706,
        longitude: 126.9775,
        description: null,
        address: '서울특별시 중구 남대문로1길 57-1',
        category: 'recommendation',
        image_url: null,
      },
      {
        id: 11,
        name: '행복전집 북창점',
        latitude: 37.563207,
        longitude: 126.977515,
        description: null,
        address: '서울특별시 중구 남대문로1길 46',
        category: 'recommendation',
        image_url: null,
      },
      {
        id: 12,
        name: '삼우정 본점',
        latitude: 37.563277,
        longitude: 126.975723,
        description: null,
        address: '서울특별시 중구 태평로1가 31-25',
        category: 'recommendation',
        image_url: null,
      },
      {
        id: 13,
        name: '남촌회관 시청본점',
        latitude: 37.567072,
        longitude: 126.978412,
        description: null,
        address: '서울특별시 중구 태평로1가 31-25',
        category: 'recommendation',
        image_url: null,
      },
      {
        id: 14,
        name: '농민백암순대 시청직영점',
        latitude: 37.562544,
        longitude: 126.977213,
        description: null,
        address: '서울특별시 중구 남대문로1길 33',
        category: 'recommendation',
        image_url: null,
      },
      {
        id: 15,
        name: '은행골 시청점',
        latitude: 37.56236,
        longitude: 126.976654,
        description: null,
        address: '서울특별시 중구 세종대로 70-1',
        category: 'recommendation',
        image_url: null,
      },
      {
        id: 16,
        name: '소호정 무교점',
        latitude: 37.567364,
        longitude: 126.97854,
        description: null,
        address: '서울특별시 중구 태평로1가 31-19',
        category: 'recommendation',
        image_url: null,
      },
      {
        id: 17,
        name: '카페 소포라',
        latitude: 37.567533,
        longitude: 126.973929,
        description: null,
        address: '서울특별시 중구 덕수궁길 114',
        category: 'recommendation',
        image_url: null,
      },
      {
        id: 18,
        name: '아티클 광화문',
        latitude: 37.567933,
        longitude: 126.975196,
        description: null,
        address: '서울 중구 세종대로21길 33',
        category: 'recommendation',
        image_url: null,
      },
      {
        id: 19,
        name: '카페마마스 시청점',
        latitude: 37.567264,
        longitude: 126.979517,
        description: null,
        address: '서울특별시 중구 무교로 16',
        category: 'recommendation',
        image_url: null,
      },
      {
        id: 20,
        name: '나이스카페인클럽 태평로점',
        latitude: 37.563605,
        longitude: 126.977571,
        description: null,
        address: '서울특별시 중구 남대문로1길 57-1',
        category: 'recommendation',
        image_url: null,
      },
      {
        id: 21,
        name: '카페아이엠티 cafe imt 시청2청사점',
        latitude: 37.566942,
        longitude: 126.979314,
        description: null,
        address: '서울 중구 서소문로 124',
        category: 'recommendation',
        image_url: null,
      },
      {
        id: 22,
        name: '올리브',
        latitude: 37.563589,
        longitude: 126.977522,
        description: null,
        address: '서울특별시 중구 세종대로18길 10',
        category: 'recommendation',
        image_url: null,
      },
      {
        id: 23,
        name: '푸르파파 북창동 직영점',
        latitude: 37.562873,
        longitude: 126.977077,
        description: null,
        address: '서울특별시 중구 태평로2가 69-1',
        category: 'recommendation',
        image_url: null,
      },
      {
        id: 24,
        name: '뽀송 스테이션 서울시청역 1번 출구',
        latitude: 37.564389,
        longitude: 126.976684,
        description: null,
        address: '서울특별시 중구 소공동 1',
        category: 'station',
        image_url: null,
      },
      {
        id: 25,
        name: '뽀송 스테이션 서울시청역 9번 출구',
        latitude: 37.562889,
        longitude: 126.974191,
        description: null,
        address: '서울특별시 중구 서소문동 75-83',
        category: 'station',
        image_url: null,
      },
      {
        id: 26,
        name: '뽀송 스테이션 서울시청역 4번 출구',
        latitude: 37.566809,
        longitude: 126.977518,
        description: null,
        address: '서울특별시 중구 태평로 1가',
        category: 'station',
        image_url: null,
      },
      {
        id: 27,
        name: '뽀송 스테이션 서울시청역 7번 출구',
        latitude: 37.564344,
        longitude: 126.977249,
        description: null,
        address: '서울특별시 중구 태평로2가 세종대로 92',
        category: 'station',
        image_url: null,
      },
      {
        id: 28,
        name: '스타벅스 시청점',
        latitude: 37.566246,
        longitude: 126.979883,
        description: null,
        address: '서울특별시 중구 을지로 19 삼성화재 삼성빌딩 1 층',
        category: 'sponsor',
        image_url: null,
      },
      {
        id: 29,
        name: '스타벅스 한국프레스센터점',
        latitude: 37.567172,
        longitude: 126.977744,
        description: null,
        address: '서울특별시 중구 태평로1가 25',
        category: 'sponsor',
        image_url: null,
      },
    ],
    skipDuplicates: true,
  });

  // StoreHashtag 관계 데이터 삽입
  await prisma.storeHashtag.createMany({
    data: [
      { storeId: 1, hashtagId: 2 },
      { storeId: 2, hashtagId: 2 },
      { storeId: 3, hashtagId: 1 },
      { storeId: 4, hashtagId: 2 },
      { storeId: 5, hashtagId: 2 },
      { storeId: 6, hashtagId: 2 },
      { storeId: 7, hashtagId: 4 },
      { storeId: 8, hashtagId: 2 },
      { storeId: 9, hashtagId: 2 },
      { storeId: 10, hashtagId: 2 },
      { storeId: 11, hashtagId: 1 },
      { storeId: 12, hashtagId: 1 },
      { storeId: 13, hashtagId: 1 },
      { storeId: 14, hashtagId: 2 },
      { storeId: 15, hashtagId: 2 },
      { storeId: 16, hashtagId: 1 },
      { storeId: 17, hashtagId: 1 },
      { storeId: 18, hashtagId: 3 },
      { storeId: 19, hashtagId: 3 },
      { storeId: 20, hashtagId: 3 },
      { storeId: 21, hashtagId: 3 },
      { storeId: 22, hashtagId: 3 },
      { storeId: 23, hashtagId: 2 },
    ],
    skipDuplicates: true,
  });
}

main()
  .then(() => console.log('✅ Seed data inserted'))
  .catch((e) => console.error(e))
  .finally(async () => {
    await prisma.$disconnect();
  });
